# ======================================================
# Spring
# ======================================================
spring.application.name=pricesentinel
server.port=8080

# ======================================================
# H2
# ======================================================
spring.datasource.url=jdbc:h2:file:./database/pricesentinel
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ======================================================
# Scheduler
# ======================================================
pricesentinel.scheduler.enabled=true
pricesentinel.scheduler.delay=60000
pricesentinel.scheduler.cron=0 0 8,12,16,20 * * *

# ======================================================
# Notification
# ======================================================
pricesentinel.notification.enabled=true

# ======================================================
# Email
# ======================================================
pricesentinel.email.enabled=false
pricesentinel.email.host=
pricesentinel.email.port=
pricesentinel.email.username=
pricesentinel.email.password=

# ======================================================
# Telegram
# ======================================================
pricesentinel.telegram.enabled=false
pricesentinel.telegram.bot-token=
pricesentinel.telegram.chat-id=

# ======================================================
# Discord
# ======================================================
pricesentinel.discord.enabled=false
pricesentinel.discord.webhook=

# ======================================================
# Logging
# ======================================================
logging.level.br.com.azk.pricesentinel=INFO